- name: Deploy Frontend
  hosts: all

  tasks:

  - name: Create root
    file:
      path: "{{ config.basedir }}/html"
      state: directory
      recurse: true

  - name: Copy static resources
    copy:
      src: ../../build/
      dest: "{{ config.basedir }}/html"

  - name: Copy configuration
    template:
      src: "templates/default.conf"
      dest: "{{ config.basedir }}"

  - name: Create network
    docker_network:
      name: "oda"

  - name: Run container
    docker_container:
      image: "nginx"
      name: "oda-ui"
      networks:
        - name: "oda"
      published_ports: "{{ config.ports }}"
      volumes:
        - "{{ config.basedir }}/html:/usr/share/nginx/html:ro"
        - "{{ config.basedir }}/default.conf:/etc/nginx/conf.d/default.conf:ro"
      restart_policy: unless-stopped
      state: started
